#!/command/with-contenv sh
set -x   # bật debug log
export DISPLAY=:0
CHROME_FLAGS="${CHROME_FLAGS:-}"
exec /root/.cache/ms-playwright/chromium-1187/chrome-linux/chrome \
  --no-sandbox \
  --disable-dev-shm-usage \
  --start-maximized \
  --remote-debugging-port=9223 \
  --remote-debugging-address=0.0.0.0 \
  --remote-allow-origins=* $CHROME_FLAGS