version: "3.9"

services:
  chrome:
    image: chrome-gui:latest
    container_name: chrome-gui
    build: .
    ports:
      - "8080:8080"        # noVNC
      - "${DEBUG_PORT:-9224}:${DEBUG_PORT:-9224}"  # remote debugging
    environment:
      - DEBUG_PORT=${DEBUG_PORT:-9224}
      - CHROME_FLAGS=${CHROME_FLAGS:-}
